### ISSUE TITLE
unsupported Laravel 6.0

### ISSUE THREAD

**Issue by hihuangwei** [subfission/cas#72] opened 2019-09-04 13:29 UTC

**Comment by regnilk** [comment] 2019-10-14 13:27
I made a fork to adapt it to laravel 6 and to have it work until the next release of the main package.

In your composer.json just add  : 
`"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/regnilk/cas"
        }
    ],`

Then require the version 3.0 of regnilk/cas.

**Comment by subfission** [comment] 2019-11-22 06:16
I don't currently use L6.0.  Feel free to make a pull request.

**Comment by wingfranky** [comment] 2019-12-09 02:06
I am using laravel v6.6.2 for development. The regnilk/cas works properly for me. Since the parent version support laravel 6.x, I want to move from forked version regnilk/cas back to subfission/cas.

However the installation failed:
1. composer require subfission/cas:3.0.0
    [InvalidArgumentException]
    Could not find package subfission/cas in a version matching 3.0.0

2. composer require "subfission/cas" "dev-master#3.0.0"
    Problem 1
    - Installation request for subfission/cas dev-master#3.0.0 -> satisfiable by subfission/cas[dev-master].
    - Conclusion: remove laravel/framework v6.6.2
    - Conclusion: don't install laravel/framework v6.6.2
    - subfission/cas dev-master requires illuminate/support 5.x -> satisfiable by 
      illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2.x-dev,........ v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/support 5.5.x-dev|don't install laravel/framework v6.6.2
    .......
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework v6.6.2
   - Installation request for laravel/framework (locked at v6.6.2, required as ^6.0) -> satisfiable by laravel/framework[v6.6.2].
Installation failed, reverting ./composer.json to its original content.

**Comment by subfission** [comment] 2019-12-10 03:56
This appears to have been caused by a missing tag: 3.0.0 instead of v3.0.0.  Should be fixed now, so give it a shot.

**Comment by wingfranky** [comment] 2019-12-18 04:02
Thanks! I installed it successfully with:
    composer require "subfission/cas":"v3.0.0"

**Comment by subfission** [comment] 2019-12-18 11:14
Awesome possum!

**Closed as completed by subfission** 2019-12-18 11:14 UTC
Labels: details requested
